sudo: false
language: node_js
node_js:
- 'node'
cache:
  directories:
    - node_modules
notifications:
  email: false
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    branch: master